# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FIFTH
author: Michal Švácha
claim: Attempting blogging. Again.

description: >
  Fifth incarnation of my personal blog. This time it's different...trust me.
keywords: "education, software, programming, czech, career"

baseurl: ""
url: "https://svachmic.github.io"
#url: "http://127.0.0.1:4000"

twitter_username: miguelitinho
github_username: svachmic
google_analytics: UA-61928196-1

# Build settings
markdown: kramdown
theme: minima
